config/routes.rb
Rails.application.routes.draw do
    
   root 'pages#home'    
    
  get '/home', to: 'pages#home'
  

  
  resources :recipes do
    member do
      post 'like'
      
    
    end
  
  end
  
  resources :chefs, exept: [:new]
  
  get '/register', to: 'chefs#new'
  
  
end

app/models/chef.rb
class Chef < ActiveRecord::Base
    has_many :recipes
    has_many :likes
    before_save { self.email = email.downcase }
    validates :chefname, presence: true, length: { minimum: 3, maximum: 40 }
    VALID_EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
    validates :email, presence: true, length: { maximum: 105 },
                                      uniqueness: { case_sensitive: false },
                                      format: { with: VALID_EMAIL_REGEX }
                                      
   has_secure_password
    
end

app/models/like.rb
class Like < ActiveRecord::Base
   belongs_to :chef
   belongs_to :recipe
   
   validates_uniqueness_of :chef, scope: :recipe

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
    belongs_to :chef
    has_many :likes
    validates :chef_id, presence: true
    validates :name, presence: true, length: { minimum: 5, maximum: 100 }
    validates :summary, presence: true, length: { minimum: 10, maximum: 150 }
    validates :description, presence: true, length: { minimum: 20, maximum: 500 }
    mount_uploader :picture, PictureUploader
    validate :picture_size
    default_scope -> { order(updated_at: :desc) }
    
    def thumps_up_total
      self.likes.where(like: true).size
    end
    
    def thumps_down_total
      self.likes.where(like: false).size
    end
    
    private
    
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "picture should be less than 5MB")
      end
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  def new
      
      @chef = Chef.new
  end
  
  
  
  def create
     @chef = Chef.new(chef_params)
      if @chef.save
      flash[:success] = "You have an account successfully created :)"
      redirect_to recipes_path
      else
       render 'new'
      end
      
  end
  

  
  def edit
    @chef = Chef.find(params[:id])
     
  end
  
  def update
    @chef = Chef.find(params[:id])
      if @chef.update(chef_params)
       flash[:success] = "Your profile has been updated"
       redirect_to recipes_path #create chefpage
      else
        render 'edit'
      end
      
  end
  
  def show
   @chef = Chef.find(params[:id])
   @recipes = @chef.recipes.paginate(page: params[:page], per_page: 4)
  end
  
  def index
    @chefs = Chef.paginate(page: params[:page], per_page: 4)
  end
  
  
  private
  
    def chef_params
        params.require(:chef).permit(:chefname, :email, :password)
    end
  

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def home
    end
    
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    
    def index
    @recipes = Recipe.paginate(page: params[:page], per_page: 5)
    end
    
    def show
    @recipe = Recipe.find(params[:id])
    end
    
    def new
        @recipe = Recipe.new
    end
    
    def create
    @recipe = Recipe.new(recipe_params)
    @recipe.chef = Chef.find(3)
    
      if @recipe.save
          flash[:success] = "Your recipe was created successfully :)"
          redirect_to recipes_path
        #do
      else
        render :new
      end
    
    end
    
    def edit
      @recipe = Recipe.find(params[:id]) 
    end
    
    def update
     @recipe = Recipe.find(params[:id])
     if @recipe.update(recipe_params)
         #do anything
        flash[:success] = "The recipe was updated"
         redirect_to recipe_path(@recipe)
     else
         render :edit
     end
    end
    
    def like 
     @recipe = Recipe.find(params[:id])
     like = Like.create(like: params[:like], chef: Chef.first, recipe: @recipe)
     if like.valid?
     flash[:success] = "Your selection was successful"
     redirect_to :back
      else
        flash[:danger] = "You can only like/dislike once"
        redirect_to :back
     end
    end
    
    
    private
    
    def recipe_params
        params.require(:recipe).permit(:name, :summary, :description, :picture)
    end
    

    


end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def gravatar_for(chef, options = { size: 80 })
        gravatar_id = Digest::MD5::hexdigest(chef.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: chef.chefname, class: "gravatar")
    end
end

app/views/chefs/_form.html.erb
<%= render 'shared/errors', obj: @chef, title: "Edit your profile" %>

<div class="row">
    
    <div class="col-md-6 col-md-offset-3 center well">
        <%= form_for @chef do |f| %>
        <%= f.label :chefname %>
        <br>
        <%= f.text_field :chefname %>
        <br>
        
        <%= f.label :email %>
        <br>
        <%= f.email_field :email %>
        <br>
        <%= f.label :password %>
        <br>
        <%= f.password_field :password %>
        
       
        <br>
        <%= f.submit(@chef.new_record? ? 'Register' : 'Edit Profile', class: "btn btn-success") %>
        
    </div>
</div>
<% end %>

app/views/chefs/edit.html.erb
<%= render 'shared/title_pages', title: "Edit your profile" %>

 <%= render 'form' %>

app/views/chefs/index.html.erb
<%= render 'shared/title_pages', title: "All Chefs" %>
<hr/>

<%= will_paginate class: "center pagination-lg" %>

<% @chefs.each do |chef| %>


<div class="row">

    <div class="col-lg-8 col-md-offset-2 well">
        <section class="center">
            <%= link_to gravatar_for(chef, size: 150), chef_path(chef) %>
            <h5>Chef: <%= chef.chefname %></h5>
         
        </section>
        
       
       
    </div>
   </div>

<% end %>


<%= will_paginate class: "center" %>

app/views/chefs/new.html.erb
<%= render 'shared/title_pages', title: "Register your account" %>

 <%= render 'form' %>

app/views/chefs/show.html.erb
<%= render 'shared/title_pages', title: "Chef: " + @chef.chefname %>

<hr/>
<div>
     <div>
      <p class="center">
         <%= gravatar_for @chef, size: 230 %>
      </p>
    </div>
   </div>
<hr/>
 <h3 class="center">My Recipes</h3>
 <%= will_paginate @recipes, class: "center pagination-lg" %>
  <% @recipes.each do |recipe| %> 
 <div class="row">
     <div class="col-md-8 col-md-offset-2 well">
       <p class="image_profile pull-left">
            <%= image_tag(recipe.picture.url, size: "200x80", class: "gravatar") if recipe.picture %>
        </p>
   <div class="pull-top">      
   <h3><%= link_to recipe.name, recipe_path(recipe) %></h3>
        <p><%= recipe.summary %></p>
        <p>
        <span class='quiet'><small>Created:&nbsp<%= time_ago_in_words(recipe.created_at) %></small></span><br>
         <span class='quiet'><small>Updated:&nbsp<%= time_ago_in_words(recipe.updated_at) %></small></span>
        </p>
        
        <div class="center">
           <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
           <i class="glyphicon glyphicon-thumbs-up"></i>&nbsp <%= recipe.thumps_up_total %>
           <% end %> &nbsp&nbsp&nbsp
           <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
           <i class="glyphicon glyphicon-thumbs-down"></i>&nbsp <%= recipe.thumps_down_total %>
           <% end %>
           </div>  
         </div>
    </div>
</div>
 <% end %>  
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
  
  <p>&copy; My recipes 2015</p>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
    
    <div class="col-md-6">
        <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %>
        <a class="close" data-dismiss="alert">&#215</a>
        </div>
        <% end %>
    </div>
</div>

app/views/layouts/_navbar.html.erb
<Header class="navbar navbar-fixed-top navbar-default">
    <div class="container">
     <div>
       <%= link_to "my Recipes", root_path, id: "logo" %>
       </div>
      <ul class="nav nav-tabs">
        <li  role:"presentation">
        <%= link_to "Recipes", recipes_path %></li>
       <li  role:"presentation">
        <%= link_to "Chefs", chefs_path %></li>
      
     <li  role:"presentation">
        <%= link_to "Create new", new_recipe_path %></li>
     </ul>
    </div>
</Header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My recipes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <%= render 'layouts/navbar' %>
<div class"container">
    <%= render 'layouts/messages' %>
<%= yield %>

<%= render 'layouts/footer' %>
</div>
</body>
</html>

app/views/pages/home.html.erb
<div class="center jumbotron">
    
    
  <h1>Welcome</h1>
  
  <h2>This is the home page for all you can eat</h2>
  <%= link_to "Sign up!!", "", class: "btn btn-lg btn-success"%>
 
  <div class="row images">
  <div class="col-md-6 col-md-offset-3">
    <a href="#" class="thumbnail">
      <img src="..." alt="...">
    </a>
    <a href="#" class="thumbnail">
      <img src="..." alt="...">
    </a>
   
  </div>
  
</div>
</div>
<div class="row center">
    <div class="col-lg-4">
        <h3 class="midrow">
            Recipes
        </h3>
    <h4>Browse and view all the recipes</h4>
    <p><%= link_to "Browse Recipes", recipes_path, class: "btn btn-warning btn-small" %></p>
</div>
 <div class="col-lg-4">
        <h3 class="midrow">
            View all the content
        </h3>
    <h4>Browse and view .........</h4>
    <p><%= link_to "Browse Recipes", "", class: "btn btn-warning btn-small" %></p>
</div>
 <div class="col-lg-4">
        <h3 class="midrow">
            View all the content
        </h3>
    <h4>Browse and view ......</h4>
    <p><%= link_to "Browse Recipes", "", class: "btn btn-warning btn-small" %></p>
</div>

</div>

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>

<div class="row">
    
    <div class="col-md-6 col-md-offset-3 center well">
        <%= form_for(@recipe, html: { multipart: true }) do |f| %>
        <%= f.label :name %>
        <br>
        <%= f.text_field :name %>
        <br>
        
        <%= f.label :summary %>
        <br>
        <%= f.text_field :summary %>
        <br>
        <%= f.label :description %>
        <br>
        <%= f.text_area :description, rows: 9 %>
        
        <span class="picture">
            <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
        </span>
        <br>
        <%= f.submit(@recipe.new_record? ? 'Create Recipe' : 'Edit Recipe', class: "btn btn-success") %>
        
    </div>
</div>
<% end %>

app/views/recipes/edit.html.erb
<%= render 'shared/title_pages', title: "Edit your Recipe" %>
 
 <%= render 'form' %>

<script type="text/javascript">
    $('#recipe_picture').bind('change', function() {
        size_in_magabytes = this.files[0].size/1024/1024;
        if (size_in_megabytes > 5) {
            alert('Maximum 5 MB. Please choose a smaller filesize');
        }
    });
    
</script>

app/views/recipes/index.html.erb
<%= render 'shared/title_pages', title: "All Recipes" %>
<hr/>

<%= will_paginate class: "center pagination-lg" %>

<% @recipes.each do |recipes| %>
<div class="container">



    <div class="col-lg-8 col-md-offset-2 well">
        <section class="chef_info center pull-left">
            <%= gravatar_for recipes.chef, size: 100 %>
            <h5>Chef: <%= recipes.chef.chefname %></h5>
         
        </section>
        
        <h3><%= link_to recipes.name, recipe_path(recipes) %></h3>
        <p><%= recipes.summary %></p>
        <p>
        <span class='quiet'><small>Created:&nbsp<%= time_ago_in_words(recipes.created_at) %></small></span><br>
         <span class='quiet'><small>Updated:&nbsp<%= time_ago_in_words(recipes.updated_at) %></small></span>
        </p>
         <p class="image_profile pull-top-right">
            <%= image_tag(recipes.picture.url, size: "250x130", class: "gravatar") if recipes.picture %>
        </p>
        <div class="pull-left">
           <%= link_to like_recipe_path(recipes, like: true), method: :post do %>
           <i class="glyphicon glyphicon-thumbs-up"></i>&nbsp <%= recipes.thumps_up_total %>
           <% end %> &nbsp&nbsp&nbsp
           <%= link_to like_recipe_path(recipes, like: false), method: :post do %>
           <i class="glyphicon glyphicon-thumbs-down"></i>&nbsp <%= recipes.thumps_down_total %>
           <% end %>
          </div>
        </div>
       
    </div>
   

<% end %>
<div> <h5 class="center"><%= link_to 'Create a new recipe', new_recipe_path, class: "btn btn-success btn-small" %></h5></div>

<%= will_paginate class: "center" %>

app/views/recipes/new.html.erb
<%= render 'shared/title_pages', title: "Create a new Recipe" %>

 <%= render 'form' %>


<script type="text/javascript">
    $('#recipe_picture').bind('change', function() {
        size_in_magabytes = this.files[0].size/1024/1024;
        if (size_in_megabytes > 5) {
            alert('Maximum 5 MB. Please choose a smaller filesize');
        }
    });
    
</script>

app/views/recipes/show.html.erb
<%= render 'shared/title_pages', title: @recipe.name %>

 
 <div class="row">
     <div class="col-md-2 col-md-offset-1">
         <%= link_to gravatar_for(@recipe.chef, size: 150), chef_path(@recipe.chef) %>
         <p>
            Chefname:<%= @recipe.chef.chefname %>
         </p>
  
    </div>
         
    
     <div class="col-md-6 col-md-offset-1">
       
         <hr/>
         <h4><%= simple_format@recipe.summary %></h4>
          <div class="show_recipe">
            <%= image_tag(@recipe.picture.url, size: "250x130", class: "gravatar") if @recipe.picture %>
        </div>
         <br>
         <div class="well">
         <p class="underline">Description:</p>
        
           <%= @recipe.description %><br>
           <div class="pull-left">
           <%= link_to like_recipe_path(@recipe, like: true), method: :post do %>
           <i class="glyphicon glyphicon-thumbs-up"></i>&nbsp <%= @recipe.thumps_up_total %>
           <% end %> &nbsp&nbsp&nbsp
           <%= link_to like_recipe_path(@recipe, like: false), method: :post do %>
           <i class="glyphicon glyphicon-thumbs-down"></i>&nbsp <%= @recipe.thumps_down_total %>
           <% end %>
          </div>
           <%= link_to "Edit recipe", edit_recipe_path, class: "btn btn-small pull-right" %>
           <br>
          
         </div>
        
       
    
     </div>
 </div>
 
 <h5 class="center"><%= link_to 'Return to Recipes', recipes_path, class: "btn btn-success btn-small" %></h5>
 <h5 class="center"><%= link_to 'Create a new recipe', new_recipe_path, class: "btn btn-danger btn-small" %></h5>

app/views/shared/_errors.html.erb
 <% if obj.errors.any? %>

 <div class="row">
    
    <div class="alert alert-danger col-md-6 col-md-offset-3 center">
        <h5>Please fill the form correctly</h5>
        
        <ul>
            <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
     </div>
   </div>
  <% end %>

app/views/shared/_title_pages.html.erb
<p>
    <h1 class="center"><%= title %></h1>
</p>